title: false
description: false
background: /assets/site-bg.webp
theme_color: '#5577EE'
timezone: Asia/Singapore

show_downloads: false
show_autogen: true
google_analytics:

twitter:
  card: summary

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-sitemap